//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityNoteSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesTB
    {
        public int NoteID { get; set; }
        public Nullable<byte> Exam1 { get; set; }
        public Nullable<byte> Exam2 { get; set; }
        public Nullable<byte> Exam3 { get; set; }
        public Nullable<byte> Quiz1 { get; set; }
        public Nullable<byte> Quiz2 { get; set; }
        public Nullable<byte> Project { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<int> Lesson { get; set; }
        public Nullable<int> Student { get; set; }
    
        public virtual LessonTB LessonTB { get; set; }
        public virtual StudentTB StudentTB { get; set; }
    }
}
