//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityNoteSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTB()
        {
            this.NotesTB = new HashSet<NotesTB>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public string StudentNumber { get; set; }
        public string StudentPassword { get; set; }
        public string StudentMail { get; set; }
        public string StudentPicture { get; set; }
        public Nullable<int> StudentDepartment { get; set; }
        public Nullable<bool> StudentStatus { get; set; }
    
        public virtual DepartmentTB DepartmentTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesTB> NotesTB { get; set; }
    }
}
